# Generated by Django 3.2.5 on 2022-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gogo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
