# Generated by Django 3.2.5 on 2022-02-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_gogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gogo',
        ),
    ]
