# Generated by Django 3.2.5 on 2022-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('user', '0004_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='movie.Movie'),
        ),
    ]
